# Generated by Django 4.2.16 on 2024-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], max_length=1)),
                ('breed', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('AWAITING_ADOPTION', 'Awaiting Adoption'), ('IN_ADOPTION', 'In Adoption'), ('ADOPTED', 'Adopted')], max_length=50)),
            ],
        ),
    ]
